# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1089, 844)
        self.draw = QtWidgets.QPushButton(parent=Dialog)
        self.draw.setGeometry(QtCore.QRect(320, 610, 401, 171))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.draw.setFont(font)
        self.draw.setObjectName("draw")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.draw.setText(_translate("Dialog", "THE BUTTON"))
